routes:
  - name: user
    path: /user
    upstream: http://localhost:8081
    auth: true
    rate_limit:
      rate: 10
      max: 10
  - name: order
    path: /order
    upstream: http://localhost:8082
    auth: false
    rate_limit:
      rate: 10
      max: 10
